# Generated by Django 5.2.5 on 2025-09-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=50)),
                ('nome_real', models.CharField(max_length=50, null=True)),
                ('poderes', models.TextField()),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('historia', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
